import { launchMe } from './mockedMeHarness.mjs'
import assert from 'node:assert/strict'
import { mkdirSync, writeFileSync } from 'node:fs'
const output = process.env.ME_PURGE_QA_OUTPUT || '/tmp/me-purge-confirmation'
mkdirSync(output, { recursive: true })
let mode = 'ready', pending = [], count = 0, executions = 0, cancelledExecutions=0, cancelledPreviews=0, resumes=0, finishExecution
let durable=[]
const plans=new Map()
const reportFor=(id,state='partial')=>({id,parentId:'fixture-parent',serial:'fixture-serial',package:'fixture.package',state,localState:state==='completed'?'completed':'pending',deviceState:state==='completed'?'completed':'failed',warnings:[],error:state==='completed'?null:'interrupted fixture device failure'})
const makePlan = (args) => {
 const now = Date.now()
 return {id:`fixture-plan-${++count}`,parentId:args.parentId,serial:'fixture-serial',package:'fixture.package',createdUnixMs:now,expiresUnixMs:now+300000,confirmationToken:`nonce-${count}`,localOnly:false,localEntries:[],warnings:[],device:{status:mode === 'offline' ? 'offline' : mode === 'not-required' ? 'not_required' : 'ready',entries:[],warnings:mode === 'offline' ? ['fixture offline reason'] : []},...(mode === 'expired' ? {createdUnixMs:now-300001,expiresUnixMs:now-1} : {}),...(mode === 'empty-token' ? {confirmationToken:''} : {})}
}
const harness = await launchMe({url:'http://127.0.0.1:1420/tests/browser/purgeConfirmationFixture.html',handler:async(command,args)=>{
 if(command === 'prepare_kernsight_group_purge' || command === 'prepare_kernsight_group_purge_retry') {
  if(mode === 'prepare-error') throw new Error('device inspect 超过120秒；未执行删除')
  const p=makePlan({parentId:args.parentId || 'fixture-parent'});plans.set(p.id,p)
  if(mode === 'pending') return await new Promise(resolve => pending.push(()=>resolve(p)))
  return p
 }
 if(command === 'cancel_kernsight_group_purge_preparation') {cancelledPreviews++;return null}
 if(command === 'list_kernsight_group_purges') return durable
 if(command === 'get_kernsight_group_purge_plan') {const p=plans.get(args.planId);assert.ok(p);return {...p,confirmationToken:''}}
 if(command === 'cancel_kernsight_group_purge') {cancelledExecutions++;const r=reportFor(args.planId,mode==='cancel-before-start'?'prepared':'partial');durable=[r];return r}
 if(command === 'resume_kernsight_group_purge') {resumes++;return await new Promise(resolve=>{finishExecution=resolve})}
 if(command === 'execute_kernsight_group_purge' && (mode==='execution-pending' || mode==='cancel-before-start')) {executions++;return await new Promise(resolve=>{finishExecution=resolve})}
 if(command === 'execute_kernsight_group_purge') { executions++; const r={id:args.planId,parentId:'fixture-parent',serial:'fixture-serial',package:'fixture.package',state:mode === 'partial'?'partial':'completed',localState:mode === 'partial'?'pending':'completed',deviceState:mode === 'partial'?'failed':'completed',warnings:[],error:mode === 'partial'?'fixture device failure':null};durable=[r];return r }
}})
const {page,calls,errors,close}=harness
const yes=()=>page.locator('.danger-button')
const retry=()=>page.getByRole('button',{name:'重新核对并重试',exact:true})
const reason=()=>page.getByTestId('purge-block-reason')
const checks=[]
const record=name=>{checks.push(name);console.log('PASS '+name)}
const waitReady=async()=>{await page.waitForFunction(()=>!document.querySelector('.danger-button').disabled)}
async function setState(value){await page.evaluate(v=>Object.assign(window.__purgeState,v),value)}
async function refresh(nextMode){mode=nextMode;await retry().click();await page.waitForTimeout(100)}
try {
 await waitReady();assert.equal(executions,0);assert.equal(await page.getByRole('checkbox').count(),0);record('ready plan automatically enables one yes without scope input or deletion')
 await refresh('not-required');await waitReady();record('not-required safe device scope enables confirmation')
 await refresh('empty-token');assert.equal(await yes().isDisabled(),true);assert.match(await reason().innerText(),/凭证/);assert.equal(await retry().isEnabled(),true);record('silent false token failure now explains and allows recheck')
 await refresh('expired');assert.equal(await yes().isEnabled(),true);assert.match(await reason().innerText(),/失效/);const beforeExpiry=executions;mode='ready';await yes().dblclick();await page.waitForTimeout(100);assert.equal(executions,beforeExpiry+1);record('expired preview refreshes and executes exactly once from one confirmation')
 durable=[];mode='expired';await setState({visible:false});await page.waitForTimeout(50);await setState({visible:true});await page.waitForTimeout(100);const beforeCancelled=executions;mode='pending';await yes().click();await page.waitForTimeout(50);await page.getByRole('button',{name:'否',exact:true}).click();pending.splice(0).forEach(resolve=>resolve());await page.waitForTimeout(100);assert.equal(executions,beforeCancelled);record('No cancels the same-Yes refresh intent and drops its late preview')
 mode='expired';await setState({visible:true});await page.waitForTimeout(100);mode='pending';await yes().click();await page.waitForTimeout(50);mode='ready';await setState({target:{parentId:'other-parent',serial:'fixture-serial',package:'fixture.package',importedRoots:[]}});pending.splice(0).forEach(resolve=>resolve());await page.waitForTimeout(100);assert.equal(executions,beforeCancelled);record('target switch invalidates confirmation intent during automatic refresh');await setState({target:{parentId:'fixture-parent',serial:'fixture-serial',package:'fixture.package',importedRoots:[]}})
 durable=[];mode='ready';await setState({visible:false});await page.waitForTimeout(50);await setState({visible:true});await waitReady();await refresh('offline');assert.equal(await yes().isDisabled(),true);assert.match(await reason().innerText(),/fixture offline reason/);assert.equal(executions,beforeExpiry+1);record('offline reason visible and retry enabled without local-only bypass');await page.screenshot({path:output+'/offline-reason.png'})
 await refresh('prepare-error');assert.equal(await yes().isEnabled(),true);assert.match(await page.getByRole('alert').innerText(),/超过120秒/);assert.equal(await retry().isEnabled(),true);assert.equal(await page.getByRole('button',{name:'正在核对…',exact:true}).count(),0);record('backend timeout stops preparing and retains retry beside exact error');const beforeMissing=executions;mode='ready';await yes().click();await page.waitForTimeout(100);assert.equal(executions,beforeMissing+1);durable=[];await setState({visible:false});await page.waitForTimeout(50);await setState({visible:true});await waitReady();record('missing preview retries within the same Yes after failure')
 mode='ready';await setState({busy:true});assert.equal(await yes().isDisabled(),true);assert.match(await reason().innerText(),/尚未结束/);await setState({busy:false});await waitReady();record('busy transition invalidates scope then automatically prepares after idle')
 mode='pending';await retry().click();await page.waitForTimeout(50);assert.equal(await yes().isDisabled(),true);assert.match(await reason().innerText(),/正在自动核对/);assert.equal(await page.getByRole('button',{name:'正在核对…',exact:true}).isDisabled(),true);await page.screenshot({path:output+'/preparing-reason.png'})
 await setState({active:false});assert.match(await reason().innerText(),/未激活/);mode='ready';await setState({active:true});await waitReady();pending.splice(0).forEach(resolve=>resolve());await page.waitForTimeout(100);assert.equal(await yes().isEnabled(),true);record('inactive-to-active retries automatically and late superseded preview cannot overwrite')
 mode='pending';await retry().click();await page.waitForTimeout(50);await setState({target:{parentId:'other-parent',serial:'fixture-serial',package:'fixture.package',importedRoots:[]}});await page.waitForTimeout(50);assert.equal(pending.length,2);pending[0]();await page.waitForTimeout(50);assert.equal(await yes().isDisabled(),true);pending[1]();pending=[];await waitReady();assert.equal(executions,beforeMissing+1);record('target race keeps old async preview from enabling foreign confirmation')
 mode='partial';await setState({target:{parentId:'fixture-parent',serial:'fixture-serial',package:'fixture.package',importedRoots:[]}});await waitReady();await yes().click();await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/fixture device failure/);assert.equal(await retry().isEnabled(),true);const first=executions;mode='ready';await retry().click();await waitReady();assert.ok(calls.some(c=>c.command==='get_kernsight_group_purge_plan'));assert.equal(await yes().innerText(),'继续已确认清理');assert.equal(executions,first);record('partial keeps local error and explicit retry only re-previews durable remaining plan')
 durable=[];await setState({visible:false});await page.waitForTimeout(50);await setState({visible:true});await waitReady()
 mode='cancel-before-start';const previousExec=executions;const previousResume=resumes;const previewsBefore=calls.filter(c=>c.command==='prepare_kernsight_group_purge').length;await yes().click();await page.waitForTimeout(50);await page.getByRole('button',{name:'停止清理并保留记录',exact:true}).click();await page.waitForTimeout(100);assert.equal(durable[0].state,'prepared');const cancelledPlanId=durable[0].id;finishExecution(reportFor(cancelledPlanId,'completed'));await page.waitForTimeout(50);mode='ready';await retry().click();await waitReady();assert.equal(await yes().innerText(),'是，永久删除本地与手机');assert.equal(calls.filter(c=>c.command==='prepare_kernsight_group_purge').length,previewsBefore+1);assert.equal(calls.filter(c=>c.command==='prepare_kernsight_group_purge_retry').length,0);assert.equal(resumes,previousResume);assert.equal(executions,previousExec+1);const freshPlanId=[...plans.keys()].at(-1);assert.notEqual(freshPlanId,cancelledPlanId);await yes().click();await page.waitForTimeout(100);assert.equal(executions,previousExec+2);assert.equal(durable[0].id,freshPlanId);record('cancel before backend start rejects old authorization; fresh preview gets new plan and a new Yes, never resume or prepareRetry')
 durable=[];await setState({visible:false});await page.waitForTimeout(50);await setState({visible:true});await waitReady()
 // A preview watchdog must ask the backend to cancel, then ignore its late result.
 mode='pending';await setState({operationTimeouts:{prepareMs:100,executeMs:100,stopMs:500}});await retry().click();await page.waitForTimeout(250);assert.equal(await retry().isEnabled(),true);assert.ok(cancelledPreviews>0);assert.match(await page.getByRole('alert').innerText(),/已请求后台停止/);const stale=pending.splice(0);mode='ready';await retry().click();await waitReady();stale.forEach(resolve=>resolve());await page.waitForTimeout(50);assert.equal(await yes().isEnabled(),true);record('preview hard timeout cancels backend, releases preparing and ignores late scope')
 mode='execution-pending';const before=cancelledExecutions;await yes().evaluate(el=>{el.click();el.click()});await page.waitForTimeout(250);assert.equal(cancelledExecutions,before+1);assert.equal(await page.evaluate(()=>window.__purgeState.executionBusy),false);assert.match(await page.getByRole('alert').innerText(),/interrupted/);const after=await page.evaluate(()=>window.__purgeState.completed.length);finishExecution(reportFor(durable[0].id,'completed'));await page.waitForTimeout(50);assert.equal(await page.evaluate(()=>window.__purgeState.completed.length),after);record('execution deadline cancels actual backend job and late success cannot overwrite durable interrupted report')
 mode='ready';await retry().click();await waitReady();assert.equal(await yes().innerText(),'继续已确认清理');await setState({operationTimeouts:{prepareMs:3000,executeMs:3000,stopMs:500}});await yes().click();await page.waitForTimeout(50);const priorCancels=cancelledExecutions;await page.getByRole('button',{name:'停止清理并保留记录',exact:true}).evaluate(el=>{el.click();el.click()});await page.waitForTimeout(100);assert.equal(resumes,1);assert.equal(cancelledExecutions,priorCancels+1);assert.equal(await page.evaluate(()=>window.__purgeState.executionBusy),false);record('already confirmed same-scope resume adds no second confirmation, double stop is single-flight')
 mode='ready';await retry().click();await waitReady();await yes().click();await page.waitForTimeout(50);const beforeUnmount=await page.evaluate(()=>window.__purgeState.completed.length);const unmountCancels=cancelledExecutions;await setState({visible:false});await page.waitForTimeout(100);assert.equal(cancelledExecutions,unmountCancels+1);assert.equal(await page.evaluate(()=>window.__purgeState.executionBusy),false);finishExecution(reportFor(durable[0].id,'completed'));await page.waitForTimeout(50);assert.equal(await page.evaluate(()=>window.__purgeState.completed.length),beforeUnmount);record('unmount cancels owned execution, releases parent busy and drops late report')
 assert.deepEqual(errors,[]);await page.screenshot({path:output+'/confirmation.png'});writeFileSync(output+'/results.json',JSON.stringify({passed:true,checks,executions,mockedIpc:true,realDeviceCalls:0},null,2))
} catch(error){await page.screenshot({path:output+'/failure.png'});writeFileSync(output+'/failure.json',JSON.stringify({error:String(error),calls,errors},null,2));throw error} finally{await close()}
