import { launchMe } from './mockedMeHarness.mjs'
import assert from 'node:assert/strict'
import { mkdirSync,writeFileSync } from 'node:fs'
const out=process.env.ME_LONG_FIELDS_QA_OUTPUT || '/tmp/me-long-fields-qa';mkdirSync(out,{recursive:true})
const abi=['arm64-v8a','armeabi-v7a','armeabi','x86_64','x86','riscv64-extension-long-architecture']
const kernel='Linux localhost 6.1.99-android14-11-g123456789abcdef-ab12345678 #1 SMP PREEMPT Wed Oct 7 01:23:45 UTC 2026 aarch64'
const hash='0123456789abcdef'.repeat(4),git='03e97b4'+'a'.repeat(33)
const curl='curl 8.7.1 (aarch64-apple-darwin23.0) libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.61.0\nRelease-Date: 2024-03-27\nProtocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp\nFeatures: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM SPNEGO SSL threadsafe UnixSockets'
const tools=[['ADB','adb','Android Debug Bridge version 1.0.41\nVersion 35.0.2-12147458\nInstalled as /opt/android/platform-tools/adb'],['Frida CLI','frida','17.15.3'],['Frida scanner','frida-ps','17.15.3'],['Python','python3','Python 3.12.10'],['curl','curl',curl],['xz','xz','xz (XZ Utils) 5.8.1\nliblzma 5.8.1'],['ideviceinfo','ideviceinfo','ideviceinfo 1.3.0-277-g123456789abcdef'],['Unknown version','iproxy',''],['Missing tool','idevice_id','']].map(([name,executable,output])=>({name,executable,available:executable!=='idevice_id',version:output.split('\n')[0],versionOutput:output,path:'/very/long/path/to/host/tools/with/multiple/directories/'+executable,versionError:executable==='iproxy'?'版本检测超时，警告详情 '+'详细原因'.repeat(40):null,versionOutputTruncated:executable==='xz',group:'frida',category:'system'}))
tools.find(t=>t.executable==='frida-ps').versionOutput=undefined
const device={platform:'android',serial:'mock-only-no-device',status:'device',model:'Pixel mock',product:'mock'}
const details={...device,manufacturer:'Google',androidVersion:'14',sdkVersion:'34',buildNumber:'very-long-build-fingerprint-'.repeat(6),architecture:'aarch64',architectureFamily:'arm64',rootStatus:'Root',selinuxStatus:'Enforcing',bootloaderStatus:'Unlocked',ipAddress:'192.0.2.1',kernelVersion:kernel,abiList:abi,securityPatch:'2026-10-01',brand:'Google'}
let overview={agentVersion:'0.2.12',agentBuildIdentity:{version:'0.2.12+03e97b4.dirty',gitCommit:git,gitDirty:true,source:'git',binarySha256:hash},protocolMajor:1,protocolMinor:0,status:{last_batch_sequence:0,session_count:0,spool_used_bytes:0,heartbeat_monotonic_ns:1},sessions:[],privatePackageBytes:0,publicPackageBytes:0}
const analysis={platform:'android',path:'/mock.apk',fileName:'mock.apk',fileSize:1000,artifactSha256:hash,packageId:'org.example.longfields',displayName:'Long fields fixture',architectures:abi,frameworks:[],thirdPartyLibraries:[],protection:{status:'未命中',packers:[],indicators:[]},antiInstrumentation:{status:'not-detected',candidates:[],indicators:[]},scanCoverage:{complete:true,warnings:[]},...Object.fromEntries(['permissions','components','exportedComponents','intentFilters','manifestFlags','files','sensitiveItems','rawInventory','binaryInsights','codeInsights','dataBoundaries','masvsObservations','verificationRecipes','findings','toolsUsed','missingDependencies'].map(k=>[k,[]]))}
const fixtures={list_devices:[device],get_device_details:details,inspect_environment:{hostOs:'macos',hostArch:'aarch64',tools,hostFridaToolsMatch:true,deviceFridaReachable:true,deviceFridaRequiresDeveloperImage:false},probe_android_monitor_capabilities:{...details,agentStatus:'Installed',btfStatus:'available',recommendedMode:'development',trustLevel:'dev',checks:[],warnings:[]},list_kernsight_package_dumps:[],analyze_app:analysis,list_knowledge:[]}
const h=await launchMe({fixtures,handler:command=>command==='get_kernsight_overview'?overview:undefined})
const {page,errors,calls,close}=h
const checks=[];const record=name=>{checks.push(name);console.log('PASS '+name)}
const full=(label)=>page.getByRole('button',{name:'复制完整'+label,exact:true}).locator('..')
async function bounded(selector){for(const e of await page.locator(selector).all()){if(!await e.isVisible())continue;const b=await e.evaluate(el=>({client:el.clientWidth,scroll:el.scrollWidth,width:innerWidth,left:el.getBoundingClientRect().left,right:el.getBoundingClientRect().right}));assert.ok(b.scroll<=b.client+1,JSON.stringify(b));assert.ok(b.left>=0&&b.right<=b.width+1,JSON.stringify(b))}}
async function copy(label,value){await full(label).getByRole('button').click();assert.equal(await page.evaluate(()=>window.__copied.at(-1)),value)}
try{
 await page.evaluate(()=>{window.__copied=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>window.__copied.push(text)}})})
 await full('ABI List').waitFor();assert.equal(await full('ABI List').locator('.full-value-text').textContent(),abi.join(', '));assert.equal(await full('Kernel').first().locator('.full-value-text').textContent(),kernel);await copy('ABI List',abi.join(', '));await copy('Build Number',details.buildNumber)
 for(const width of [1440,821,390]){await page.setViewportSize({width,height:1000});await bounded('.spec-grid .full-value');await page.locator('.device-card').screenshot({path:`${out}/devices-${width}.png`})}record('Compact ABI/kernel/build values copy complete originals at 1440, 821, and 390 pixels')
 await page.getByTitle('运行时分析 · Frida、DEX 与 Native',{exact:true}).click();await page.locator('.environment-card').waitFor();
 const curlCard=page.locator('.tool-status').filter({has:page.locator('strong').filter({hasText:/^curl$/})});assert.equal(await full('curl 版本输出').locator('.full-value-text').textContent(),curl);await copy('curl 版本输出',curl)
 await full('curl 版本输出').getByRole('button').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>window.__copied.at(-1)),curl);await copy('curl 路径',tools.find(t=>t.executable==='curl').path)
 assert.equal(await page.locator('.tool-version-details summary, .full-value-copy').count(),0)
 assert.match(await page.locator('.environment-card').innerText(),/版本未知/);assert.match(await page.locator('.environment-card').innerText(),/版本检测超时/);assert.match(await page.locator('.environment-card').innerText(),/仅保留前 32 KiB/);assert.match(await page.locator('.environment-card').innerText(),/未安装/);assert.match(await page.locator('.environment-card').innerText(),/未提供完整原始输出，此处仅显示版本摘要/)
 for(const width of [1440,821,390]){await page.setViewportSize({width,height:1000});await bounded('.tool-status, .tool-status .full-value');await page.locator('.environment-card').screenshot({path:`${out}/frida-${width}.png`})}record('Complete multiline tool output/path, keyboard value-copy, missing/unknown/warning/truncation states remain accessible at all sizes')
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('denied')}}}));await full('curl 版本输出').getByRole('button').click();assert.match(await full('curl 版本输出').getByRole('alert').innerText(),/复制失败.*手动复制/);assert.equal(await page.locator('.full-value-preview').filter({has:page.locator('small').filter({hasText:'curl 版本输出 ·'})}).locator('pre').textContent(),curl);record('Clipboard failure opens complete selectable preview and clear manual-copy feedback')
 await page.evaluate(()=>{window.__pendingCopies=0;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:text=>{window.__pendingCopies++;window.__pendingText=text;return new Promise(resolve=>window.__resolveCopy=resolve)}}})})
 await full('curl 版本输出').getByRole('button').evaluate(el=>{el.click();el.click()});assert.equal(await page.evaluate(()=>window.__pendingCopies),1);assert.equal(await full('curl 版本输出').getByRole('button').isDisabled(),true)
 tools.find(t=>t.executable==='curl').versionOutput=curl+'\nUpdated version output'
 await page.getByRole('button',{name:/重新检测 Frida 环境/}).click();await page.waitForFunction(()=>document.querySelector('.tool-version-details .full-value-text')&&[...document.querySelectorAll('.full-value-text')].some(e=>e.textContent.endsWith('Updated version output')))
 await page.evaluate(()=>window.__resolveCopy());await page.waitForTimeout(30);assert.equal(await full('curl 版本输出').getByRole('status').count(),0);assert.equal(await page.evaluate(()=>window.__pendingText),curl);assert.equal(await full('curl 版本输出').getByRole('button').isEnabled(),true)
 record('Repeated copy clicks execute once; late clipboard completion cannot claim success for a newer tool value')
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>window.__copied.push(text)}}))
 await full('curl 路径').getByRole('button').hover();assert.equal(await page.locator('.full-value-preview').filter({has:page.locator('small').filter({hasText:'curl 路径 ·'})}).locator('pre').textContent(),tools.find(t=>t.executable==='curl').path)
 const beforeSelectionCopy=await page.evaluate(()=>window.__copied.length)
 await full('curl 路径').locator('.full-value-text').evaluate(el=>{const selection=window.getSelection();selection.removeAllRanges();const range=document.createRange();range.selectNodeContents(el);selection.addRange(range);el.click()})
 assert.equal(await page.evaluate(()=>window.__copied.length),beforeSelectionCopy);await page.evaluate(()=>window.getSelection().removeAllRanges())
 await full('curl 路径').getByRole('button').click({modifiers:['Shift']});assert.equal(await page.evaluate(()=>window.__copied.length),beforeSelectionCopy)
 record('Hover exposes full original; selected text and modifier clicks never overwrite clipboard')

 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>window.__copied.push(text)}}))
 await page.getByTitle('KernSight · 采集、会话与 L2 证据',{exact:true}).click();await page.getByRole('button',{name:'fact_check 检测设备能力',exact:true}).click();await page.locator('.runtime-device-strip').getByText('KernSight 0.2.12+03e97b4.dirty',{exact:true}).waitFor();await page.locator('.agent-build-details summary').click();await copy('KernSight Git commit',git);await copy('Agent binary SHA-256',hash)
 for(const width of [1440,821,390]){await page.setViewportSize({width,height:1000});await bounded('.runtime-device-strip .full-value, .runtime-device-strip > div');await page.locator('.runtime-device-strip').screenshot({path:`${out}/kern-${width}.png`})}record('Device-reported short build identity, dirty marker, full Git commit and binary SHA copy render without clipping')
 overview={...overview,agentBuildIdentity:null};await page.getByRole('button',{name:/刷新会话与证据/}).click();await page.getByText('Git commit 未知（旧 Agent 或未提供有效构建信息）',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'复制完整KernSight Git commit',exact:true}).count(),0);assert.match(await page.locator('.agent-build-details').innerText(),/工作区状态：未知/);record('Older agents retain base version and explicit unknown commit/dirty state without invented identity')
 await page.getByTitle('静态分析 · APK / IPA 清单与证据',{exact:true}).click();await page.getByPlaceholder('/absolute/path/to/app.apk or app.ipa').fill('/mock.apk');await page.getByRole('button',{name:'开始分析',exact:true}).click();await full('Artifact SHA-256').waitFor();await copy('Artifact SHA-256',hash)
 for(const width of [1440,821,390]){await page.setViewportSize({width,height:1000});await bounded('.app-summary-grid .full-value');await page.locator('.app-summary-grid').screenshot({path:`${out}/analyzer-${width}.png`})}record('Analyzer shows and copies all 64 SHA-256 characters and long architecture list at all sizes')
 assert.deepEqual(errors,[]);writeFileSync(out+'/results.json',JSON.stringify({passed:true,checks,errors,commands:[...new Set(calls.map(c=>c.command))],note:'Cloud Chromium; mocked Tauri IPC only; no phone commands or real artifacts.'},null,2))
}catch(error){await page.screenshot({path:out+'/failure.png',fullPage:true});writeFileSync(out+'/failure.txt',String(error)+'\n'+JSON.stringify({calls,errors},null,2));throw error}finally{await close()}
