import assert from 'node:assert/strict'
import {mkdirSync,writeFileSync} from 'node:fs'
import {launchMe} from './mockedMeHarness.mjs'
import {fileURLToPath} from 'node:url'
import {resolve} from 'node:path'
import {tmpdir} from 'node:os'
const projectRoot=fileURLToPath(new URL('../../',import.meta.url))
const out=resolve(process.env.ME_DEX_SELECTION_QA_OUTPUT||resolve(tmpdir(),'me-dex-selection-qa'));mkdirSync(out,{recursive:true})
const ids=['aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa','bbbbbbbb-2222-4222-8222-bbbbbbbbbbbb']
const groups=ids.map((id,i)=>({schema:'mobilee.capture-group/v1',id,serial:'mock-only-no-device',package:'org.example.dex',createdUnixMs:1791500000000+i,state:'partial',cancelRequested:false,unified:false,base:{},stages:[{id:'stage-'+id,key:'linker',mode:'linker',durationSeconds:15,required:true,launchAfterAttach:false,attempts:[{relation:{parentId:id,stageId:'stage-'+id,attemptId:'attempt-'+id,attempt:1,stageKey:'linker'},state:'partial',startedUnixMs:1791500000000,finishedUnixMs:1791500025000,sessionId:'child-'+id,error:'synthetic partial retained'}]}]}))
const sha=i=>i.toString(16).padStart(64,'0')
function bundle(root,i,objectCount,fileCount){const path=`runtime/${root}-container.bound.code`,objects=Array.from({length:objectCount},(_,n)=>({sha256:sha(i*100+n+1),bytes:n+100,sources:[{kind:'retained',relative_path:path}],classes:[`Lfixture/${root}/Class${n};`],indexed_classes:1,declared_classes:1,class_index_status:'complete_class_def_index',validation_status:'unknown',ownership:'unknown'}));return {root:'/mock/'+root,package:'org.example.dex',fileCount,totalBytes:10000,files:objectCount?[{relativePath:path,bytes:2000,category:'runtime'},...Array.from({length:fileCount-1},(_,n)=>({relativePath:`forensics/${root}-file-${String(n).padStart(3,'0')}.json`,bytes:1,category:'metadata'}))]:[],captureText:'',importedUnixMs:1791500100000+i,dumpReport:{package:'org.example.dex',dump_id:root,dex_sets:[],content_dex_class_index:{schema:'mobilee.content-dex-class-index/v1',scope:'synthetic browser acceptance only',objects},local_storage_accounting:{logical_file_bytes:10000,allocated_bytes:10000,verified_code_duplicate_bytes:0,runtime_observations:[]},http_calls:[{host:root+'.example.invalid',path:'/only-'+root,method:'GET',origin:'synthetic L2'}]},sessionReport:{schema_version:'fixture',session_id:groups[Math.min(i,1)].stages[0].attempts[0].sessionId,mobilee_capture_group:groups[Math.min(i,1)]}}}
const a=bundle('root-A',0,40,130),b=bundle('root-B',1,2,2),empty=bundle('root-empty',2,0,0)
delete empty.sessionReport
a.files[0].codeEvidence=[{relative_path:a.files[0].relativePath,sha256:sha(1),source_complete:false,local_content_status:'complete_range_hash_verified',write_status:'retained',read:{read_status:'short_read'}}]
a.dumpReport.dex_ownership={schema_version:'mobilee.kernsight-dex-ownership/v4',package:a.package,entries:Array.from({length:40},(_,n)=>({sha256:sha(n+1),canonical_relative_path:a.files[0].relativePath+'#DEX-'+n,category:'unknown',confidence:0,sampled_classes:1,business_classes:0,internal_classes:0,third_party_classes:0,unknown_classes:1,dominant_namespaces:['Lfixture/root-A'],reasons:['synthetic ownership stays unknown']})),business:0,internal_components:0,third_party_sdks:0,dynamic_payloads:0,mixed:0,unknown:40}
let nextImport=a,mode='success',resolveRead
const childReport=(parentId,root)=>({sessionId:'child-'+parentId,reportSchema:'fixture',report:{session_id:'child-'+parentId,mobilee_capture_group:groups.find(g=>g.id===parentId),mobilee_capture_edges:[],execution_complete:true,mode_counts:{observe:parentId===ids[0]?31:666,inspect:2},quality:{lost_records:17},processes:[],http_calls:[],plaintext:[],network_peers:[],binder_relations:[],synthetic_source_root:root}})
const h=await launchMe({root:projectRoot,fixtures:{list_kernsight_groups:groups,list_kernsight_group_purges:[]},handler:async(command,args)=>{
 if(command==='plugin:dialog|open')return nextImport.root
 if(command==='import_kernsight_evidence_directory')return nextImport
 if(command==='local_kernsight_evidence_present')return true
 if(command==='get_local_kernsight_child_report'){if(mode==='error')throw new Error('synthetic child read unavailable');if(mode==='pending')return new Promise(resolve=>{resolveRead=()=>resolve(childReport(args.parentId,args.root))});return childReport(args.parentId,args.root)}
}})
const {page,calls,errors,close}=h,checks=[]
const record=name=>{checks.push(name);console.log('PASS '+name)}
const packagePanel=()=>page.locator('.ks-package-evidence-panel'),browser=()=>packagePanel().locator('.ks-evidence-browser'),files=()=>browser().locator('.ks-evidence-file-list > button')
const card=()=>packagePanel().locator('.ks-forensic-grid > article').filter({has:page.locator('strong').filter({hasText:'DEX 文件 / 容器'})})
const row=id=>page.locator('.ks-capture-group').filter({has:page.locator(':scope > summary').filter({hasText:id.slice(0,8)})})
const child=id=>row(id).locator('.ks-child-actions > button[aria-controls]')
async function open(id){if(!await row(id).evaluate(el=>el.open))await row(id).locator(':scope > summary').click()}
async function importBundle(item){nextImport=item;await page.getByRole('button',{name:/导入本地证据/}).click();await page.locator('.ks-package-list article').filter({hasText:item.package}).first().click();await packagePanel().waitFor()}
const interfaceTab=()=>page.locator('.ks-inline-session-detail .ks-session-detail-tabs > button').filter({hasText:/^接口 \d+$/})
try{
 await page.getByRole('button',{name:/KernSight.*采集、会话/}).click();await importBundle(a)
 assert.equal(await files().count(),100);assert.match(await browser().locator(':scope > header').innerText(),/130 catalogued/)
 await browser().getByRole('button',{name:/继续显示 30 个文件/}).click();assert.equal(await files().count(),130)
 assert.equal(await card().locator(':scope > b').innerText(),'1');assert.match(await card().innerText(),/40 个结构对象/)
 await card().click();assert.equal(await files().count(),1);assert.match(await files().innerText(),/root-A-container\.bound\.code/);assert.match(await browser().locator(':scope > header').innerText(),/1 catalogued/)
 await browser().getByRole('button',{name:'显示全部',exact:true}).click();assert.equal(await files().count(),100);assert.match(await browser().locator(':scope > header').innerText(),/130 catalogued/)
 record('Main physical-file count and filtered list agree; show-all resets a previously expanded 130-file page to 100')
 const analysis=packagePanel().locator('.ks-code-analysis');assert.match(await analysis.locator(':scope > header').innerText(),/当前采集的 DEX \/ SO 代码分析/);assert.equal(await analysis.getByRole('button',{name:'复制完整当前代码分析来源目录'}).textContent(),a.root);assert.equal(await analysis.locator(':scope > details[open]').count(),0)
 const noise=analysis.locator(':scope > .ks-code-noise');await noise.locator(':scope > summary').click();await noise.locator('details.noise-attention > summary').click();assert.match(await noise.innerText(),/root-A-container\.bound\.code/);assert.match(await noise.innerText(),/partial \/ 失败 \/ 来源状态未知/);await noise.locator(':scope > summary').click();assert.equal(await noise.evaluate(el=>el.open),false)
 const ownership=analysis.locator(':scope > .ks-code-ownership');assert.equal(await ownership.locator('.ks-dex-ownership-list > article:visible').count(),0);await ownership.locator(':scope > summary').click();assert.equal(await ownership.locator('.ks-dex-ownership-list > article:visible').count(),30);await ownership.getByRole('button',{name:'继续显示 10 个 DEX'}).click();assert.equal(await ownership.locator('.ks-dex-ownership-list > article:visible').count(),40);assert.match(await ownership.innerText(),/synthetic ownership stays unknown/);await ownership.locator(':scope > summary').click();assert.equal(await ownership.locator('.ks-dex-ownership-list > article:visible').count(),0)
 await analysis.screenshot({path:out+'/same-root-code-analysis-collapsed.png'});record('One same-source code-analysis area keeps index, noise and ownership distinct; long ownership lists expand, paginate and close locally')
 const index=packagePanel().locator('.ks-code-analysis > .ks-dex-index');assert.equal(await packagePanel().locator('.ks-code-analysis > details[open]').count(),0);await index.locator(':scope > summary').click();assert.equal(await index.locator('[data-dex-object]:visible').count(),40);await index.locator('[data-dex-object]').last().scrollIntoViewIfNeeded();assert.match(await index.locator('[data-dex-object]').last().innerText(),/Class39/);await index.locator('input').fill('Class39;');assert.match(await index.locator('[data-dex-index-status="indexed"]').last().innerText(),/匹配 1/)
 await card().click();await importBundle(b);assert.equal(await files().count(),2);assert.equal(await packagePanel().locator('.ks-forensic-grid > article.active').count(),0)
 const pick=packagePanel().locator('.ks-local-capture-picker select');await pick.selectOption(a.root);assert.equal(await files().count(),100);assert.equal(await packagePanel().locator('.ks-code-analysis > details[open]').count(),0);await index.locator(':scope > summary').click();assert.equal(await index.locator('input').inputValue(),'');assert.equal(await index.locator('[data-dex-object]:visible').count(),40)
 record('Same-package root changes reset file category/page and the actual DEX component query without merging inventories')
 await open(ids[0]);await child(ids[0]).click();await page.locator('.ks-inline-session-detail').waitFor();assert.match(await page.locator('.ks-session-package-link').innerText(),/尚未加载 L2/);assert.equal(await interfaceTab().innerText(),'接口 0')
 await page.getByRole('button',{name:'接入本次采集 L2 证据',exact:true}).click();assert.match(await page.locator('.ks-session-package-link').innerText(),/已显式接入 L2/);assert.equal(await interfaceTab().innerText(),'接口 1')
 await interfaceTab().click();assert.match(await page.locator('.ks-inline-session-detail .ks-url-board').innerText(),/root-A\.example\.invalid\/only-root-A/)
 await open(ids[1]);assert.equal(await page.locator('.ks-inline-session-detail').count(),0);await child(ids[1]).click();await page.locator('.ks-inline-session-detail').waitFor();assert.match(await page.locator('.ks-session-package-link').innerText(),/尚未加载 L2/);assert.equal(await interfaceTab().innerText(),'接口 0');assert.equal(await pick.inputValue(),b.root)
 await page.getByRole('button',{name:'接入本次采集 L2 证据',exact:true}).click();await interfaceTab().click();assert.match(await page.locator('.ks-inline-session-detail .ks-url-board').innerText(),/root-B\.example\.invalid\/only-root-B/);assert.doesNotMatch(await page.locator('.ks-inline-session-detail').innerText(),/root-A\.example\.invalid/)
 await page.getByRole('button',{name:'断开 L2 关联',exact:true}).click();assert.equal(await interfaceTab().innerText(),'接口 0');assert.equal(await page.locator('.ks-inline-session-detail .ks-url-board').count(),0)
 record('L2 remains explicitly unlinked on each current child; linking loads only that exact parent root and unlink removes its interface candidates')
 await child(ids[1]).click();mode='pending';await child(ids[1]).click();await page.locator('.ks-loading').filter({hasText:'正在重放'}).waitFor();await open(ids[0]);resolveRead();await page.waitForTimeout(50);assert.equal(await page.locator('.ks-inline-session-detail').count(),0)
 mode='error';await child(ids[0]).click();await row(ids[0]).locator('.operation-error').waitFor();assert.match(await row(ids[0]).innerText(),/synthetic child read unavailable/);assert.equal(await row(ids[0]).locator('.ks-child-actions > button').innerText(),'展开子证据');assert.equal(await packagePanel().locator('.ks-dex-index [data-dex-object]').count(),40);mode='success'
 record('Child loading, late completion and local read failure keep the prior package inventory and do not reopen old linked data')
 await importBundle(empty);assert.match(await packagePanel().locator('.ks-code-ownership > summary').innerText(),/归属依据未提供或未映射/);assert.equal(await files().count(),0);assert.match(await browser().innerText(),/当前采集记录列示 0 个文件/);if(!await index.evaluate(el=>el.open))await index.locator(':scope > summary').click();assert.match(await index.innerText(),/明确列示 0 个结构对象/)
 for(const width of [1440,821,390]){await page.setViewportSize({width,height:1000});const bounds=await packagePanel().evaluate(el=>({client:el.clientWidth,scroll:el.scrollWidth,pageClient:document.documentElement.clientWidth,pageScroll:document.documentElement.scrollWidth}));assert.ok(bounds.scroll<=bounds.client+1&&bounds.pageScroll<=bounds.pageClient+1,JSON.stringify({width,bounds}));await packagePanel().screenshot({path:out+`/empty-local-record-${width}.png`})}
 record('Loaded empty file/object inventories explain measured zero and retain readable layout at wide, medium and narrow widths')
 assert.deepEqual(errors,[]);assert.deepEqual(calls.filter(c=>/^(begin_|provision_|run_kernsight|start_|dump_|execute_|trash_|restore_|cleanup_|cancel_)/.test(c.command)),[])
 writeFileSync(out+'/browser-results.json',JSON.stringify({passed:true,checks,errors,commands:[...new Set(calls.map(c=>c.command))],note:'Synthetic exact-parent/root fixtures in actual independent Chromium Vue UI; neither a real-device 40-object count nor native ME/WebKit verification. IPC mocked, no capture/deploy/bank action.'},null,2));console.log(JSON.stringify({passed:true,checks:checks.length,out}))
}catch(error){await page.screenshot({path:out+'/failure.png',fullPage:true});writeFileSync(out+'/failure.txt',String(error)+'\n'+JSON.stringify({calls,errors},null,2));throw error}finally{await close()}
