'use strict';
function exp(n){try{return Module.getGlobalExportByName(n)}catch(e){return null}}
function native(n,r,a){const p=exp(n);return p?new NativeFunction(p,r,a):null}
function str(v){const p=Memory.allocUtf8String(v);return p}
function home(){const g=native('getenv','pointer',['pointer']);if(!g)return '/tmp';const p=g(str('HOME'));return p.isNull()?'/tmp':p.readUtf8String()}
function info(){if(typeof ObjC!=='undefined'&&ObjC.available){const b=ObjC.classes.NSBundle.mainBundle(),p=b.executablePath().toString(),d=b.infoDictionary(),n=d.objectForKey_('CFBundleDisplayName')||d.objectForKey_('CFBundleName'),h=ObjC.classes.NSProcessInfo.processInfo().environment().objectForKey_('HOME');return{appName:n?n.toString():p.split('/').pop(),bundleId:b.bundleIdentifier().toString(),bundlePath:b.bundlePath().toString(),executableName:p.split('/').pop(),sandboxPath:h.toString()}}const m=Process.mainModule,p=m.path,x=p.indexOf('.app/'),root=x>=0?p.substring(0,x+4):p.substring(0,p.lastIndexOf('/'));return{appName:root.split('/').pop().replace(/\.app$/,''),bundleId:null,bundlePath:root,executableName:m.name,sandboxPath:home()}}
function segname(p){const a=new Uint8Array(p.readByteArray(16));let s='';for(let i=0;i<a.length&&a[i];i++)s+=String.fromCharCode(a[i]);return s}
function macho(base){const m=base.readU32(),x=m===0xfeedfacf||m===0xcffaedfe;if(!x&&m!==0xfeedface&&m!==0xcefaedfe)throw new Error('Unsupported Mach-O');let c=x?32:28,b=null,k=null,a=[];const n=base.add(16).readU32();for(let i=0;i<n;i++){const q=base.add(c).readU32(),z=base.add(c+4).readU32();if(z<8)throw new Error('Invalid load command');if(q===1||q===0x19){const name=segname(base.add(c+8)),v=x?base.add(c+24).readU64().toNumber():base.add(c+24).readU32(),vs=x?base.add(c+32).readU64().toNumber():base.add(c+28).readU32(),o=x?base.add(c+40).readU64().toNumber():base.add(c+32).readU32(),fs=x?base.add(c+48).readU64().toNumber():base.add(c+36).readU32();if(name==='__TEXT'||(b===null&&o===0))b=v;a.push({v,vs,o,fs})}if(q===0x21||q===0x2c)k=c+16;c+=z}return{a,b,k}}
function dump(path){const i=info(),mod=Process.getModuleByName(i.executableName),p=macho(mod.base);if(p.b===null)throw new Error('No base segment');const f=new File(path,'wb');p.a.forEach(s=>{if(!s.fs)return;const n=Math.min(s.fs,s.vs||s.fs);f.seek(s.o,File.SEEK_SET);f.write(mod.base.add(s.v-p.b).readByteArray(n));if(n<s.fs){f.seek(s.o+s.fs-1,File.SEEK_SET);f.write(new Uint8Array([0]).buffer)}});if(p.k!==null){f.seek(p.k,File.SEEK_SET);f.write(new Uint8Array([0,0,0,0]).buffer)}f.flush();f.close();return{path,executableName:i.executableName,bundlePath:i.bundlePath}}
function files(root){if(typeof ObjC!=='undefined'&&ObjC.available){const fm=ObjC.classes.NSFileManager.defaultManager(),e=fm.enumeratorAtPath_(root),r=[];let o;while((o=e.nextObject())!==null){const rel=o.toString(),full=root+'/'+rel,d=Memory.alloc(1);d.writeU8(0);if(fm.fileExistsAtPath_isDirectory_(full,d)&&d.readU8()===0){const a=fm.attributesOfItemAtPath_error_(full,NULL),s=a?Number(a.objectForKey_('NSFileSize').toString()):0;r.push({relative:rel,size:s})}}return r}const od=native('opendir','pointer',['pointer']),rd=native('readdir','pointer',['pointer']),cd=native('closedir','int',['pointer']),r=[];const off=Process.pointerSize===8?{type:20,name:21}:{type:12,name:13};function walk(dir,rel){const d=od(str(dir));if(d.isNull())return;while(true){const e=rd(d);if(e.isNull())break;const n=e.add(off.name).readUtf8String();if(!n||n==='.'||n==='..')continue;const full=dir+'/'+n,q=rel?rel+'/'+n:n,t=e.add(off.type).readU8();if(t===4)walk(full,q);else{try{const f=new File(full,'rb');f.seek(0,File.SEEK_END);const size=Number(f.tell());f.close();r.push({relative:q,size})}catch(x){}}}cd(d)}walk(root,'');return r}
function read(path,offset,size){const f=new File(path,'rb');f.seek(offset,File.SEEK_SET);const b=f.readBytes(size);f.close();return b}
function remove(path){if(typeof ObjC!=='undefined'&&ObjC.available){ObjC.classes.NSFileManager.defaultManager().removeItemAtPath_error_(path,NULL);return true}const u=native('unlink','int',['pointer']);return u?u(str(path))===0:false}
rpc.exports={bundleinfo:info,dumpexecutable:dump,listfiles:files,readfile:read,removefile:remove};
